import type { Document, User, Category } from './types';
import { BookOpen, FlaskConical, Landmark, Microscope, BrainCircuit, Users } from 'lucide-react';

export const mockCategories: Category[] = [
  { id: 'medicina', name: 'Medicina', icon: Microscope },
  { id: 'ciencias', name: 'Ciencias de la Vida', icon: FlaskConical },
  { id: 'humanidades', name: 'Salud Pública', icon: Users },
  { id: 'psicologia', name: 'Psicología', icon: BrainCircuit },
];

export const mockDocuments: Document[] = [
  {
    id: '1',
    title: 'Principios de Anatomía y Fisiología',
    author: 'Gerard J. Tortora, Bryan H. Derrickson',
    year: 2021,
    category: 'Medicina',
    subject: 'Anatomía',
    description: 'Una obra clásica que ofrece una visión equilibrada de la anatomía y la fisiología humanas, ideal para estudiantes de ciencias de la salud.',
    tags: ['anatomía', 'fisiología', 'cuerpo humano'],
    thumbnailUrl: 'https://picsum.photos/seed/book3/400/600',
    fileUrl: '#',
    lastUpdated: '2023-10-15',
    version: 2,
  },
  {
    id: '2',
    title: 'Biología Celular y Molecular',
    author: 'Harvey Lodish',
    year: 2020,
    category: 'Ciencias de la Vida',
    subject: 'Biología Celular',
    description: 'Referencia fundamental para entender los procesos celulares a nivel molecular, con ilustraciones detalladas y explicaciones claras.',
    tags: ['biología', 'célula', 'molecular'],
    thumbnailUrl: 'https://picsum.photos/seed/book6/400/600',
    fileUrl: '#',
    lastUpdated: '2023-09-20',
    version: 1,
  },
  {
    id: '3',
    title: 'Epidemiología Básica',
    author: 'R. Beaglehole, R. Bonita, T. Kjellström',
    year: 2019,
    category: 'Salud Pública',
    subject: 'Epidemiología',
    description: 'Una introducción a los principios y métodos de la epidemiología, esencial para profesionales de la salud pública.',
    tags: ['epidemiología', 'salud pública', 'investigación'],
    thumbnailUrl: 'https://picsum.photos/seed/book7/400/600',
    fileUrl: '#',
    lastUpdated: '2023-11-01',
    version: 3,
  },
  {
    id: '4',
    title: 'Manual Diagnóstico y Estadístico de los Trastornos Mentales (DSM-5)',
    author: 'American Psychiatric Association',
    year: 2014,
    category: 'Psicología',
    subject: 'Psiquiatría',
    description: 'La guía de referencia más autorizada para el diagnóstico de trastornos mentales, utilizada por clínicos e investigadores.',
    tags: ['dsm-5', 'psicología', 'diagnóstico'],
    thumbnailUrl: 'https://picsum.photos/seed/book8/400/600',
    fileUrl: '#',
    lastUpdated: '2022-05-12',
    version: 1,
  },
  {
    id: '5',
    title: 'Fisiopatología: La base biológica de la enfermedad',
    author: 'Carol Mattson Porth',
    year: 2022,
    category: 'Medicina',
    subject: 'Fisiopatología',
    description: 'Explora los mecanismos de las enfermedades y su impacto en el funcionamiento del cuerpo humano.',
    tags: ['fisiopatología', 'enfermedad', 'medicina'],
    thumbnailUrl: 'https://picsum.photos/seed/book1/400/600',
    fileUrl: '#',
    lastUpdated: '2024-01-20',
    version: 1,
  },
  {
    id: '6',
    title: 'Genética: Un enfoque conceptual',
    author: 'Benjamin A. Pierce',
    year: 2021,
    category: 'Ciencias de la Vida',
    subject: 'Genética',
    description: 'Presenta los conceptos fundamentales de la genética de una manera accesible y atractiva para los estudiantes.',
    tags: ['genética', 'adn', 'herencia'],
    thumbnailUrl: 'https://picsum.photos/seed/book2/400/600',
    fileUrl: '#',
    lastUpdated: '2023-08-30',
    version: 2,
  },
  {
    id: '7',
    title: 'Gestión de Sistemas de Salud: Casos y Conceptos',
    author: 'Kurt Darr',
    year: 2018,
    category: 'Salud Pública',
    subject: 'Administración en Salud',
    description: 'Analiza la gestión de organizaciones sanitarias a través de estudios de caso y marcos conceptuales.',
    tags: ['gestión', 'salud', 'administración'],
    thumbnailUrl: 'https://picsum.photos/seed/book4/400/600',
    fileUrl: '#',
    lastUpdated: '2023-03-10',
    version: 1,
  },
  {
    id: '8',
    title: 'Psicología Cognitiva y sus Aplicaciones',
    author: 'John R. Anderson',
    year: 2019,
    category: 'Psicología',
    subject: 'Psicología Cognitiva',
    description: 'Un texto líder que conecta la teoría cognitiva con aplicaciones del mundo real.',
    tags: ['cognición', 'psicología', 'memoria'],
    thumbnailUrl: 'https://picsum.photos/seed/book5/400/600',
    fileUrl: '#',
    lastUpdated: '2023-07-22',
    version: 1,
  },
];

export const mockUsers: User[] = [
  {
    id: 'user-1',
    name: 'Ana García',
    email: 'admin@cayetano.edu',
    role: 'Admin',
    avatarUrl: 'https://i.pravatar.cc/150?u=admin@cayetano.edu',
    lastActivity: '2024-05-20T10:00:00Z',
    createdAt: '2022-01-10T09:00:00Z',
  },
  {
    id: 'user-2',
    name: 'Luis Fernandez',
    email: 'editor@cayetano.edu',
    role: 'Editor',
    avatarUrl: 'https://i.pravatar.cc/150?u=editor@cayetano.edu',
    lastActivity: '2024-05-19T15:30:00Z',
    createdAt: '2022-02-15T11:00:00Z',
  },
  {
    id: 'user-3',
    name: 'Carla Torres',
    email: 'user@cayetano.edu',
    role: 'User',
    avatarUrl: 'https://i.pravatar.cc/150?u=user@cayetano.edu',
    lastActivity: '2024-05-20T12:45:00Z',
    createdAt: '2023-03-20T14:00:00Z',
  },
   {
    id: 'user-4',
    name: 'Mario Rojas',
    email: 'mario.r@cayetano.edu',
    role: 'User',
    avatarUrl: 'https://i.pravatar.cc/150?u=mario.r@cayetano.edu',
    lastActivity: '2024-05-18T09:00:00Z',
    createdAt: '2023-04-01T18:00:00Z',
  },
];
